version: '3'

services:
  server:
    build: .
    volumes:
      - ./repo_replicator:/app/repo_replicator
      - ./requirements.txt:/app/requirements.txt
      - ./secrets:/app/secrets
    environment:
      - CONFIG_PATH=/app/secrets/secrets.yaml
    ports:
      - "5000:5000"
